# Generated by Django 4.2.1 on 2023-05-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='rdv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomm', models.CharField(max_length=100)),
                ('nomp', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('Time', models.CharField(max_length=100)),
                ('prix', models.CharField(max_length=100)),
                ('spec', models.CharField(max_length=100)),
            ],
        ),
    ]
