# Generated by Django 4.2.1 on 2023-05-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contact', '0005_userp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='groupsp',
            field=models.ManyToManyField(related_name='userps', to='auth.group'),
        ),
        migrations.AddField(
            model_name='userp',
            name='user_permissionsp',
            field=models.ManyToManyField(related_name='userps', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='userp',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='userp',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
