# Generated by Django 4.2.1 on 2023-05-19 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_remove_userp_groupsp_remove_userp_user_permissionsp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userp',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userp',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userp',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='last_name',
        ),
    ]
