# Generated by Django 4.2.1 on 2023-05-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_user_prix_user_role_user_spec_delete_userp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prix',
            field=models.CharField(max_length=255),
        ),
    ]
