# Generated by Django 4.2.1 on 2023-05-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_alter_user_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='yas', max_length=255),
            preserve_default=False,
        ),
    ]
