# Generated by Django 4.2.1 on 2023-05-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nomp',
            field=models.CharField(default='e', max_length=255),
            preserve_default=False,
        ),
    ]
