# Generated by Django 4.2.1 on 2023-05-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_user_nomp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='etat',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
    ]
