# Generated by Django 4.2.1 on 2023-05-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_rdv_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='messg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('nomc', models.CharField(max_length=200)),
                ('mesg', models.CharField(max_length=200)),
            ],
        ),
    ]
