# Generated by Django 4.2.1 on 2023-05-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_messg'),
    ]

    operations = [
        migrations.CreateModel(
            name='messgm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('nomc', models.CharField(max_length=200)),
                ('mesg', models.CharField(max_length=200)),
            ],
        ),
    ]
