# Generated by Django 4.2.1 on 2023-05-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_messgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='notm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('nomc', models.CharField(max_length=200)),
                ('mesg', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='notp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomp', models.CharField(max_length=200)),
                ('notp', models.CharField(max_length=200)),
            ],
        ),
    ]
